/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class ComplaintPanel extends javax.swing.JPanel {

    /**
     * Creates new form ComplaintPanel
     */
    public ComplaintPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vdbtn = new javax.swing.JButton();
        cidlb = new javax.swing.JLabel();
        enamelb = new javax.swing.JLabel();
        cdatelb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 0, 0));
        setLayout(null);

        vdbtn.setText("View Details");
        add(vdbtn);
        vdbtn.setBounds(811, 21, 163, 43);

        cidlb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cidlb.setForeground(new java.awt.Color(255, 255, 153));
        cidlb.setText("Complaint ID:");
        add(cidlb);
        cidlb.setBounds(30, 20, 640, 40);

        enamelb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        enamelb.setForeground(new java.awt.Color(255, 255, 153));
        enamelb.setText("Employee Name:");
        add(enamelb);
        enamelb.setBounds(30, 80, 610, 40);

        cdatelb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cdatelb.setForeground(new java.awt.Color(255, 255, 153));
        cdatelb.setText("Complaint Lodge Date:");
        add(cdatelb);
        cdatelb.setBounds(30, 140, 560, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel cdatelb;
    public javax.swing.JLabel cidlb;
    public javax.swing.JLabel enamelb;
    public javax.swing.JButton vdbtn;
    // End of variables declaration//GEN-END:variables
}
