/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class HelpDeskHome extends javax.swing.JFrame {

    /**
     * Creates new form HelpDeskHome
     */
    public HelpDeskHome() {
        initComponents();
        setSize(1280,720);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        agendalb = new javax.swing.JLabel();
        developerslb = new javax.swing.JLabel();
        loginlb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HelpDeskHome.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1390, 690);

        agendalb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agendalbMouseClicked(evt);
            }
        });
        getContentPane().add(agendalb);
        agendalb.setBounds(820, 180, 240, 90);

        developerslb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                developerslbMouseClicked(evt);
            }
        });
        getContentPane().add(developerslb);
        developerslb.setBounds(790, 300, 320, 70);

        loginlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginlbMouseClicked(evt);
            }
        });
        getContentPane().add(loginlb);
        loginlb.setBounds(830, 420, 210, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agendalbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agendalbMouseClicked
        new AgendaHR().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agendalbMouseClicked

    private void developerslbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_developerslbMouseClicked
        new Developers().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_developerslbMouseClicked

    private void loginlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginlbMouseClicked
        new MainPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginlbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpDeskHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpDeskHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpDeskHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpDeskHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpDeskHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agendalb;
    private javax.swing.JLabel developerslb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel loginlb;
    // End of variables declaration//GEN-END:variables
}
