
import java.sql.ResultSet;
import java.util.StringTokenizer;

public class HRHeadViewComplaints extends javax.swing.JFrame {

    String issue,status;
    
    public HRHeadViewComplaints(String iss, String st) {
        initComponents();
        issuecb.removeAllItems();
        statuscb.removeAllItems();
        issue=iss;
        status=st;
        getissues();
        getstatus();
        getComplaints(issue,status);
        setSize(1280,755);
        setLocationRelativeTo(null);
        setResizable(false);
    }
    public void getComplaints(String issue, String status) {
        try {
            ResultSet rs;
            if(issue.equals("")&&status.equals("")){
                rs = DBLoader.executeStatement("select * from ncomplaints");
            }else{
                rs = DBLoader.executeStatement("select * from ncomplaints where issue='"+issue+"' and status='"+status+"'");
            }
            int y = 10;
            while(rs.next()){
                String all="";
                ComplaintPanel obj = new ComplaintPanel();
                obj.setBounds(10, y, 770, 200);
                vcpnl.add(obj);
                int cid = rs.getInt(1);
                int eid = rs.getInt(2);
                ResultSet rs1 = DBLoader.executeStatement("select * from employeedetails where eid="+eid+"");
                String ename="";
                String phn="";
                String email="";
                if(rs1.next()){
                    ename = rs1.getString(2);
                    phn = rs1.getString(3);
                    email = rs1.getString(4);
                }
                
                int deptid = rs.getInt(3);
                String dept = "";
                ResultSet rs2 = DBLoader.executeStatement("select * from departments where deptno="+deptid+"");
                if(rs2.next()){
                    dept = rs2.getString(3);
                }
                String iss = rs.getString(4);
                String body = rs.getString(5);
                String st = rs.getString(6);
                String cdate = rs.getString(7);
                String ladate = rs.getString(8);
                String scid = Integer.toString(cid);
                String seid = Integer.toString(eid);
                all=all+"##"+scid+"##"+seid+"##"+ename+"##"+phn+"##"+email+"##"+dept+"##"+iss+"##"+body+"##"+st+"##"+cdate+"##"+ladate;
                System.out.println(all);
                StringTokenizer stt = new StringTokenizer(all, "##");
                while(stt.hasMoreTokens()){
                    String a = stt.nextToken();
                    String b = stt.nextToken();
                    String c = stt.nextToken();
                    String d = stt.nextToken();
                    String e = stt.nextToken();
                    String f = stt.nextToken();
                    String g = stt.nextToken();
                    String h = stt.nextToken();
                    String i = stt.nextToken();
                    String j = stt.nextToken();
                    String k = stt.nextToken();
                    obj.setSize(1000,200);
                    obj.cidlb.setText("Complaint ID:   " + cid);
                    obj.enamelb.setText("Employee Name:   " + ename);
                    obj.cdatelb.setText("Complaint Lodge Date:   " + cdate);
                    obj.vdbtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            HRHeadViewComplaints.this.dispose();
                            new HRHeadViewDetails(a,b,c,d,e,f,g,h,i,j,k).setVisible(true);
                    }
                });
                }
                
                            
                y = y + 220;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    
    public void getissues(){
        try {
            ResultSet rs = DBLoader.executeStatement("select * from issues");
            while(rs.next()){
                String issue = rs.getString(1);
                issuecb.addItem(issue);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void getstatus(){
        try {
            ResultSet rs = DBLoader.executeStatement("select * from status");
            while(rs.next()){
                String status = rs.getString(1);
                statuscb.addItem(status);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vcpnl = new javax.swing.JPanel();
        statuscb = new javax.swing.JComboBox<>();
        issuecb = new javax.swing.JComboBox<>();
        backlb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        vcpnl.setBackground(new java.awt.Color(255, 255, 255));
        vcpnl.setForeground(new java.awt.Color(51, 204, 0));

        javax.swing.GroupLayout vcpnlLayout = new javax.swing.GroupLayout(vcpnl);
        vcpnl.setLayout(vcpnlLayout);
        vcpnlLayout.setHorizontalGroup(
            vcpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1450, Short.MAX_VALUE)
        );
        vcpnlLayout.setVerticalGroup(
            vcpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(vcpnl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 140, 1140, 510);

        statuscb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        statuscb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                statuscbItemStateChanged(evt);
            }
        });
        getContentPane().add(statuscb);
        statuscb.setBounds(830, 60, 310, 50);

        issuecb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        issuecb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                issuecbItemStateChanged(evt);
            }
        });
        getContentPane().add(issuecb);
        issuecb.setBounds(280, 60, 310, 50);

        backlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backlbMouseClicked(evt);
            }
        });
        getContentPane().add(backlb);
        backlb.setBounds(1110, 680, 160, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRHeadViewComplaints.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void issuecbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_issuecbItemStateChanged
        issue = evt.getItem().toString();
        vcpnl.removeAll();
        getComplaints(issue, status);
    }//GEN-LAST:event_issuecbItemStateChanged

    private void statuscbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_statuscbItemStateChanged
        status = evt.getItem().toString();
        vcpnl.removeAll();
        getComplaints(issue, status);
    }//GEN-LAST:event_statuscbItemStateChanged

    private void backlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlbMouseClicked
        new HRHeadHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backlbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewComplaints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewComplaints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewComplaints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewComplaints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ViewComplaints().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backlb;
    private javax.swing.JComboBox<String> issuecb;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> statuscb;
    private javax.swing.JPanel vcpnl;
    // End of variables declaration//GEN-END:variables
}
