/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class HRHome extends javax.swing.JFrame {

    String username;
    public HRHome(String userid){
        username=userid;
        initComponents();
        setSize(1280,755);
        setLocationRelativeTo(null);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vplb = new javax.swing.JLabel();
        vclb = new javax.swing.JLabel();
        cplb = new javax.swing.JLabel();
        logoutlb = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRHome.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1280, 720);

        vplb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vplbMouseClicked(evt);
            }
        });
        getContentPane().add(vplb);
        vplb.setBounds(220, 250, 210, 80);

        vclb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vclbMouseClicked(evt);
            }
        });
        getContentPane().add(vclb);
        vclb.setBounds(460, 450, 210, 80);

        cplb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cplbMouseClicked(evt);
            }
        });
        getContentPane().add(cplb);
        cplb.setBounds(620, 260, 220, 80);

        logoutlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutlbMouseClicked(evt);
            }
        });
        getContentPane().add(logoutlb);
        logoutlb.setBounds(870, 450, 220, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutlbMouseClicked
       new MainPage().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_logoutlbMouseClicked

    private void vclbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vclbMouseClicked
        new ViewComplaints("","",username).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vclbMouseClicked

    private void cplbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cplbMouseClicked
        new HRChangePassword(username).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cplbMouseClicked

    private void vplbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vplbMouseClicked
        new HRViewProfile(username).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vplbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new HRHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cplb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logoutlb;
    private javax.swing.JLabel vclb;
    private javax.swing.JLabel vplb;
    // End of variables declaration//GEN-END:variables
}
