/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class ResponsePanel extends javax.swing.JPanel {

    /**
     * Creates new form ResponsePanel
     */
    public ResponsePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stlb = new javax.swing.JLabel();
        isslb = new javax.swing.JLabel();
        cdlb = new javax.swing.JLabel();
        vdbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 51, 0));
        setLayout(null);

        stlb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        stlb.setForeground(new java.awt.Color(255, 255, 204));
        stlb.setText("Status:");
        add(stlb);
        stlb.setBounds(20, 130, 560, 40);

        isslb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        isslb.setForeground(new java.awt.Color(255, 255, 204));
        isslb.setText("Issue:");
        add(isslb);
        isslb.setBounds(20, 30, 560, 40);

        cdlb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cdlb.setForeground(new java.awt.Color(255, 255, 204));
        cdlb.setText("Complaint Date:");
        add(cdlb);
        cdlb.setBounds(20, 80, 560, 40);

        vdbtn.setText("View Details");
        add(vdbtn);
        vdbtn.setBounds(730, 50, 150, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel cdlb;
    public javax.swing.JLabel isslb;
    public javax.swing.JLabel stlb;
    public javax.swing.JButton vdbtn;
    // End of variables declaration//GEN-END:variables
}
