/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class UserHome extends javax.swing.JFrame {

    String userid;
    public UserHome(String uid) {
        initComponents();
        userid=uid;
        System.out.println(userid);
        
        setSize(1280,755);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vplb = new javax.swing.JLabel();
        cplb = new javax.swing.JLabel();
        logoutlb = new javax.swing.JLabel();
        trlb = new javax.swing.JLabel();
        lclb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserHome.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1290, 720);

        vplb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vplbMouseClicked(evt);
            }
        });
        getContentPane().add(vplb);
        vplb.setBounds(220, 250, 200, 80);

        cplb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cplbMouseClicked(evt);
            }
        });
        getContentPane().add(cplb);
        cplb.setBounds(630, 250, 200, 90);

        logoutlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutlbMouseClicked(evt);
            }
        });
        getContentPane().add(logoutlb);
        logoutlb.setBounds(1040, 260, 210, 80);

        trlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trlbMouseClicked(evt);
            }
        });
        getContentPane().add(trlb);
        trlb.setBounds(880, 450, 220, 90);

        lclb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lclbMouseClicked(evt);
            }
        });
        getContentPane().add(lclb);
        lclb.setBounds(460, 440, 220, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vplbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vplbMouseClicked
        new UserViewProfile(userid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vplbMouseClicked

    private void cplbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cplbMouseClicked
        new ChangePassword(userid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cplbMouseClicked

    private void logoutlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutlbMouseClicked
        new MainPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutlbMouseClicked

    private void lclbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lclbMouseClicked
        new WriteComplaint(userid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lclbMouseClicked

    private void trlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trlbMouseClicked
        new UserTrackResponse(userid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_trlbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new UserHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cplb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lclb;
    private javax.swing.JLabel logoutlb;
    private javax.swing.JLabel trlb;
    private javax.swing.JLabel vplb;
    // End of variables declaration//GEN-END:variables
}
